from __future__ import annotations

from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from app.core.auth import get_current_user
from app.core.supabase import get_supabase

router = APIRouter(prefix="/reports", tags=["Reports"])


@router.get("/")
async def list_reports(
    user: dict = Depends(get_current_user),
    search: Optional[str] = Query(None),
    fabric_type: Optional[str] = Query(None),
    limit: int = Query(20, le=100),
    offset: int = Query(0),
):
    supabase = get_supabase()
    if not supabase:
        return {"reports": [], "total": 0}

    query = supabase.table("reports").select("*, uploads(file_name, file_url, file_size_kb)", count="exact").eq("user_id", user["id"])

    if fabric_type:
        query = query.eq("fabric_type", fabric_type)
    if search:
        query = query.ilike("fabric_type", f"%{search}%")

    result = query.order("created_at", desc=True).range(offset, offset + limit - 1).execute()
    return {"reports": result.data or [], "total": result.count or 0}


@router.get("/{report_id}")
async def get_report(report_id: str, user: dict = Depends(get_current_user)):
    supabase = get_supabase()
    if not supabase:
        raise HTTPException(status_code=404, detail="Report not found")

    result = (
        supabase.table("reports")
        .select("*, uploads(file_name, file_url, file_size_kb, mime_type)")
        .eq("id", report_id)
        .eq("user_id", user["id"])
        .single()
        .execute()
    )

    if not result.data:
        raise HTTPException(status_code=404, detail="Report not found")

    return {"report": result.data}


@router.delete("/{report_id}")
async def delete_report(report_id: str, user: dict = Depends(get_current_user)):
    supabase = get_supabase()
    if not supabase:
        return {"message": "Report deleted"}

    supabase.table("reports").delete().eq("id", report_id).eq("user_id", user["id"]).execute()
    return {"message": "Report deleted"}


@router.get("/{report_id}/download")
async def download_report(report_id: str, user: dict = Depends(get_current_user)):
    supabase = get_supabase()
    if not supabase:
        raise HTTPException(status_code=404, detail="Report not found")

    result = (
        supabase.table("reports")
        .select("*, uploads(file_name, file_url)")
        .eq("id", report_id)
        .eq("user_id", user["id"])
        .single()
        .execute()
    )

    if not result.data:
        raise HTTPException(status_code=404, detail="Report not found")

    report = result.data
    upload = report.get("uploads", {})

    report_text = f"""ThreadCounty Fabric Analysis Report
=====================================
Report ID: {report['id']}
Generated: {report.get('created_at', 'N/A')}

File: {upload.get('file_name', 'Unknown')}

ANALYSIS RESULTS
----------------
Thread Density: {report.get('thread_density')} threads/inch
Warp Count: {report.get('warp_count')}
Weft Count: {report.get('weft_count')}
Fabric Type: {report.get('fabric_type')}
Confidence Score: {float(report.get('confidence_score', 0)) * 100:.1f}%

AI SUGGESTIONS
--------------
"""
    for i, suggestion in enumerate(report.get("ai_suggestions", []), 1):
        report_text += f"{i}. {suggestion}\n"

    report_text += "\n--- Generated by ThreadCounty AI Platform ---\n"

    return {"content": report_text, "filename": f"threadcounty-report-{report_id[:8]}.txt"}
